language: cpp
compiler:
- clang
notifications:
email: false
env:
matrix:
- JULIAVERSION="juliareleases"
- JULIAVERSION="julianightlies"
before_install:
- sudo add-apt-repository ppa:staticfloat/julia-deps -y
- sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
- sudo apt-get update -qq -y
- sudo apt-get install libpcre3-dev julia -y
- sudo apt-get install libXxf86vm-dev # GLFW dependencies
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fiscript:
- julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.test("GLAbstraction")'
